<?php $this->load->view('header.php'); ?>
<?php if(!isset($act) || $act != 'pdf') { $this->load->view('sidebar.php'); } ?>

    <!-- bootstrap datepicker -->
    <link rel="stylesheet" href="<?php echo base_url();?>bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
    <style>
        .report-container { padding-top: 15px; }
        .report-container > div { padding: 10px 0px; }
        .report-container > div > span { padding-bottom: 3px; border-bottom: 1px dashed #999; }
    </style>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper" style="background: none;">
        <?php if(!isset($act) || $act != 'pdf') { ?><!-- Content Header (Page header) -->
        <section class="content-header">
            <h1 class="visible-xs">
                <?php echo isset($page_header) && $page_header != '' ? $page_header : ''; ?>
            </h1>
            <h1 class="hidden-xs">
                <?php echo isset($page_header) && $page_header != '' ? $page_header : ''; ?>
            </h1>
        </section>
        <?php } ?>
        <!-- Main content -->
        <section class="content container-fluid cust-container-fluid d-flex h-100">

            <!--------------------------
              | Your Page Content Here |
              -------------------------->

            <!-- general form elements -->
            <div class="box box-primary box-pdf"><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
                <div class="box-body" <?php echo isset($act) && $act == 'pdf' ? 'style="border-top: none;margin-top:-15px;"' : '';?> >
                    <div class="row report-container" style="margin: 0;">
                        <!-- div class="col-xs-12 col-md-12 text-center">Monthly Report</div -->
                        <div class="col-xs-12 col-md-12 text-center"><span style="font-family: 'erasbd'; font-size: 22px;"><?php echo $PropertyInfo['property_name'];?></span></div>
                        <div class="col-xs-12 col-md-12 text-center"><span style="font-family: 'erasbd'; font-size: 22px;">Statement of Account</span></div>
                        <div class="col-xs-12 col-md-12 text-center"><span style="font-family: 'erasbd'; font-size: 19px;"><?php echo !empty($_GET['from']) ? date("d-F-Y", strtotime($_GET['from'])) : '01-'. date('M-Y');?> to <?php echo !empty($_GET['to']) ? date("d-F-Y", strtotime($_GET['to'])) : date('d-m-Y');?></span></div>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Modal -->


    <!-- bootstrap datepicker -->
<?php if (isset($act) && $act == 'pdf') {
    // echo '<div class="col-xs-12 col-md-12" style="padding-top:25px;"> Report Generated By <b>'.$_SESSION['bms']['full_name'].' ['.$gen_by_desi[0]['desi_name'].']</b> On <b>'. date('d-m-Y h:i:s a') .'</b></div>';
    echo '</body></html>';
} ?>